config/routes.rb
Rails.application.routes.draw do
get 'personals/ascn/*'=> 'personals#ascn', as: 'ascn'
get 'personals/ascname/*'=> 'personals#ascname', as: 'ascname'
get 'peronals/indexx' => 'personals#indexx', as: 'indexx'

  resources :professions, :sabhas, :families, :academics, :personals

get 'google' => redirect('http://www.google.com')

root 'personals#index' 

  
	

end

app/models/academic.rb
class Academic < ActiveRecord::Base
belongs_to :personal
end

app/controllers/academics_controller.rb
class AcademicsController < ApplicationController
  before_action :set_academic, only: [:show, :edit, :update, :destroy]

  # GET /academics
  # GET /academics.json
  def index
    @academics = Academic.all
  end

  # GET /academics/1
  # GET /academics/1.json
  def show
  end

  # GET /academics/new
  def new
    @academic = Academic.new
  end

  # GET /academics/1/edit
  def edit
  end

  # POST /academics
  # POST /academics.json
  def create
    @academic = Academic.new(academic_params)

    respond_to do |format|
      if @academic.save
        format.html { redirect_to @academic, notice: 'Academic was successfully created.' }
        format.json { render :show, status: :created, location: @academic }
      else
        format.html { render :new }
        format.json { render json: @academic.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /academics/1
  # PATCH/PUT /academics/1.json
  def update
    respond_to do |format|
      if @academic.update(academic_params)
        format.html { redirect_to @academic, notice: 'Academic was successfully updated.' }
        format.json { render :show, status: :ok, location: @academic }
      else
        format.html { render :edit }
        format.json { render json: @academic.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /academics/1
  # DELETE /academics/1.json
  def destroy
    @academic.destroy
    respond_to do |format|
      format.html { redirect_to academics_url, notice: 'Academic was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_academic
      @academic = Academic.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def academic_params
      params.require(:academic).permit(:personals_aygcode, :stream, :qualification, :current_edu, :college, :coaching)
    end
end

app/helpers/academics_helper.rb
module AcademicsHelper
end

app/views/academics/_form.html.erb
<%= form_for(@academic) do |f| %>
  <% if @academic.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@academic.errors.count, "error") %> prohibited this academic from being saved:</h2>

      <ul>
      <% @academic.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :personals_aygcode %><br>
    <%= f.text_field :personals_aygcode %>
  </div>
  <div class="field">
    <%= f.label :stream %><br>
    <%= f.text_field :stream %>
  </div>
  <div class="field">
    <%= f.label :qualification %><br>
    <%= f.text_field :qualification %>
  </div>
  <div class="field">
    <%= f.label :current_edu %><br>
    <%= f.text_field :current_edu %>
  </div>
  <div class="field">
    <%= f.label :college %><br>
    <%= f.text_field :college %>
  </div>
  <div class="field">
    <%= f.label :coaching %><br>
    <%= f.text_field :coaching %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/academics/edit.html.erb
<h1>Editing Academic</h1>

<%= render 'form' %>

<%= link_to 'Show', @academic %> |
<%= link_to 'Back', academics_path %>

app/views/academics/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Academics</h1>

<table>
  <thead>
    <tr>
      <th>Personals aygcode</th>
      <th>Stream</th>
      <th>Qualification</th>
      <th>Current edu</th>
      <th>College</th>
      <th>Coaching</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @academics.each do |academic| %>
      <tr>
        <td><%= academic.personals_aygcode %></td>
        <td><%= academic.stream %></td>
        <td><%= academic.qualification %></td>
        <td><%= academic.current_edu %></td>
        <td><%= academic.college %></td>
        <td><%= academic.coaching %></td>
        <td><%= link_to 'Show', academic %></td>
        <td><%= link_to 'Edit', edit_academic_path(academic) %></td>
        <td><%= link_to 'Destroy', academic, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Academic', new_academic_path %>

app/views/academics/new.html.erb
<h1>New Academic</h1>

<%= render 'form' %>

<%= link_to 'Back', academics_path %>

app/views/academics/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Personals aygcode:</strong>
  <%= @academic.personals_aygcode %>
</p>

<p>
  <strong>Stream:</strong>
  <%= @academic.stream %>
</p>

<p>
  <strong>Qualification:</strong>
  <%= @academic.qualification %>
</p>

<p>
  <strong>Current edu:</strong>
  <%= @academic.current_edu %>
</p>

<p>
  <strong>College:</strong>
  <%= @academic.college %>
</p>

<p>
  <strong>Coaching:</strong>
  <%= @academic.coaching %>
</p>

<%= link_to 'Edit', edit_academic_path(@academic) %> |
<%= link_to 'Back', academics_path %>