config/routes.rb
Rails.application.routes.draw do
get 'personals/ascn/*'=> 'personals#ascn', as: 'ascn'
get 'personals/ascname/*'=> 'personals#ascname', as: 'ascname'
get 'peronals/indexx' => 'personals#indexx', as: 'indexx'

  resources :professions, :sabhas, :families, :academics, :personals

get 'google' => redirect('http://www.google.com')

root 'personals#index' 

  
	

end

app/models/sabha.rb
class Sabha < ActiveRecord::Base
end

app/controllers/sabhas_controller.rb
class SabhasController < ApplicationController
  before_action :set_sabha, only: [:show, :edit, :update, :destroy]

  # GET /sabhas
  # GET /sabhas.json
  def index
    @sabhas = Sabha.all
  end

  # GET /sabhas/1
  # GET /sabhas/1.json
  def show
  end

  # GET /sabhas/new
  def new
    @sabha = Sabha.new
  end

  # GET /sabhas/1/edit
  def edit
  end

  # POST /sabhas
  # POST /sabhas.json
  def create
    @sabha = Sabha.new(sabha_params)

    respond_to do |format|
      if @sabha.save
        format.html { redirect_to @sabha, notice: 'Sabha was successfully created.' }
        format.json { render :show, status: :created, location: @sabha }
      else
        format.html { render :new }
        format.json { render json: @sabha.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /sabhas/1
  # PATCH/PUT /sabhas/1.json
  def update
    respond_to do |format|
      if @sabha.update(sabha_params)
        format.html { redirect_to @sabha, notice: 'Sabha was successfully updated.' }
        format.json { render :show, status: :ok, location: @sabha }
      else
        format.html { render :edit }
        format.json { render json: @sabha.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /sabhas/1
  # DELETE /sabhas/1.json
  def destroy
    @sabha.destroy
    respond_to do |format|
      format.html { redirect_to sabhas_url, notice: 'Sabha was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_sabha
      @sabha = Sabha.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def sabha_params
      params.require(:sabha).permit(:groupleader, :karyakarta, :reference, :sub_reference, :direct_reference, :pooja, :amrish, :kanthi)
    end
end

app/helpers/sabhas_helper.rb
module SabhasHelper
end

app/views/sabhas/_form.html.erb
<%= form_for(@sabha) do |f| %>
  <% if @sabha.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@sabha.errors.count, "error") %> prohibited this sabha from being saved:</h2>

      <ul>
      <% @sabha.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :groupleader %><br>
    <%= f.text_field :groupleader %>
  </div>
  <div class="field">
    <%= f.label :karyakarta %><br>
    <%= f.text_field :karyakarta %>
  </div>
  <div class="field">
    <%= f.label :reference %><br>
    <%= f.text_field :reference %>
  </div>
  <div class="field">
    <%= f.label :sub_reference %><br>
    <%= f.text_field :sub_reference %>
  </div>
  <div class="field">
    <%= f.label :direct_reference %><br>
    <%= f.text_field :direct_reference %>
  </div>
  <div class="field">
    <%= f.label :pooja %><br>
    <%= f.check_box :pooja %>
  </div>
  <div class="field">
    <%= f.label :amrish %><br>
    <%= f.check_box :amrish %>
  </div>
  <div class="field">
    <%= f.label :kanthi %><br>
    <%= f.check_box :kanthi %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/sabhas/edit.html.erb
<h1>Editing Sabha</h1>

<%= render 'form' %>

<%= link_to 'Show', @sabha %> |
<%= link_to 'Back', sabhas_path %>

app/views/sabhas/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Sabhas</h1>

<table>
  <thead>
    <tr>
      <th>Groupleader</th>
      <th>Karyakarta</th>
      <th>Reference</th>
      <th>Sub reference</th>
      <th>Direct reference</th>
      <th>Pooja</th>
      <th>Amrish</th>
      <th>Kanthi</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @sabhas.each do |sabha| %>
      <tr>
        <td><%= sabha.groupleader %></td>
        <td><%= sabha.karyakarta %></td>
        <td><%= sabha.reference %></td>
        <td><%= sabha.sub_reference %></td>
        <td><%= sabha.direct_reference %></td>
        <td><%= sabha.pooja %></td>
        <td><%= sabha.amrish %></td>
        <td><%= sabha.kanthi %></td>
        <td><%= link_to 'Show', sabha %></td>
        <td><%= link_to 'Edit', edit_sabha_path(sabha) %></td>
        <td><%= link_to 'Destroy', sabha, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Sabha', new_sabha_path %>

app/views/sabhas/new.html.erb
<h1>New Sabha</h1>

<%= render 'form' %>

<%= link_to 'Back', sabhas_path %>

app/views/sabhas/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Groupleader:</strong>
  <%= @sabha.groupleader %>
</p>

<p>
  <strong>Karyakarta:</strong>
  <%= @sabha.karyakarta %>
</p>

<p>
  <strong>Reference:</strong>
  <%= @sabha.reference %>
</p>

<p>
  <strong>Sub reference:</strong>
  <%= @sabha.sub_reference %>
</p>

<p>
  <strong>Direct reference:</strong>
  <%= @sabha.direct_reference %>
</p>

<p>
  <strong>Pooja:</strong>
  <%= @sabha.pooja %>
</p>

<p>
  <strong>Amrish:</strong>
  <%= @sabha.amrish %>
</p>

<p>
  <strong>Kanthi:</strong>
  <%= @sabha.kanthi %>
</p>

<%= link_to 'Edit', edit_sabha_path(@sabha) %> |
<%= link_to 'Back', sabhas_path %>