config/routes.rb
Rails.application.routes.draw do
get 'personals/ascn/*'=> 'personals#ascn', as: 'ascn'
get 'personals/ascname/*'=> 'personals#ascname', as: 'ascname'
get 'peronals/indexx' => 'personals#indexx', as: 'indexx'

  resources :professions, :sabhas, :families, :academics, :personals

get 'google' => redirect('http://www.google.com')

root 'personals#index' 

  
	

end

app/models/family.rb
class Family < ActiveRecord::Base
  belongs_to :personal
end

app/controllers/families_controller.rb
class FamiliesController < ApplicationController
  before_action :set_family, only: [:show, :edit, :update, :destroy]

  # GET /families
  # GET /families.json
  def index
    @families = Family.all
  end

  # GET /families/1
  # GET /families/1.json
  def show
  end

  # GET /families/new
  def new
    @family = Family.new
  end

  # GET /families/1/edit
  def edit
  end

  # POST /families
  # POST /families.json
  def create
    @family = Family.new(family_params)

    respond_to do |format|
      if @family.save
        format.html { redirect_to @family, notice: 'Family was successfully created.' }
        format.json { render :show, status: :created, location: @family }
      else
        format.html { render :new }
        format.json { render json: @family.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /families/1
  # PATCH/PUT /families/1.json
  def update
    respond_to do |format|
      if @family.update(family_params)
        format.html { redirect_to @family, notice: 'Family was successfully updated.' }
        format.json { render :show, status: :ok, location: @family }
      else
        format.html { render :edit }
        format.json { render json: @family.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /families/1
  # DELETE /families/1.json
  def destroy
    @family.destroy
    respond_to do |format|
      format.html { redirect_to families_url, notice: 'Family was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_family
      @family = Family.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def family_params
      params.require(:family).permit(:personals_aygcode_id, :dad_occupation, :do_description, :brothers, :sisters)
    end
end

app/helpers/families_helper.rb
module FamiliesHelper
end

app/views/families/_form.html.erb
<%= form_for(@family) do |f| %>
  <% if @family.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@family.errors.count, "error") %> prohibited this family from being saved:</h2>

      <ul>
      <% @family.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :dad_occupation %><br>
    <%= f.text_field :dad_occupation %>
  </div>
  <div class="field">
    <%= f.label :do_description %><br>
    <%= f.text_field :do_description %>
  </div>
  <div class="field">
    <%= f.label :brothers %><br>
    <%= f.number_field :brothers %>
  </div>
  <div class="field">
    <%= f.label :sisters %><br>
    <%= f.number_field :sisters %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/families/edit.html.erb
<h1>Editing Family</h1>

<%= render 'form' %>

<%= link_to 'Show', @family %> |
<%= link_to 'Back', families_path %>

app/views/families/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Families</h1>

<table>
  <thead>
    <tr>
      <th>Personals aygcode</th>
      <th>Dad occupation</th>
      <th>Do description</th>
      <th>Brothers</th>
      <th>Sisters</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @families.each do |family| %>
      <tr>
        <td><%= family.personals_aygcode %></td>
        <td><%= family.dad_occupation %></td>
        <td><%= family.do_description %></td>
        <td><%= family.brothers %></td>
        <td><%= family.sisters %></td>
        <td><%= link_to 'Show', family %></td>
        <td><%= link_to 'Edit', edit_family_path(family) %></td>
        <td><%= link_to 'Destroy', family, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Family', new_family_path %>

app/views/families/new.html.erb
<h1>New Family</h1>

<%= render 'form' %>

<%= link_to 'Back', families_path %>

app/views/families/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Personals aygcode:</strong>
  <%= @family.personals_aygcode %>
</p>

<p>
  <strong>Dad occupation:</strong>
  <%= @family.dad_occupation %>
</p>

<p>
  <strong>Do description:</strong>
  <%= @family.do_description %>
</p>

<p>
  <strong>Brothers:</strong>
  <%= @family.brothers %>
</p>

<p>
  <strong>Sisters:</strong>
  <%= @family.sisters %>
</p>

<%= link_to 'Edit', edit_family_path(@family) %> |
<%= link_to 'Back', families_path %>