config/routes.rb
Rails.application.routes.draw do
get 'personals/ascn/*'=> 'personals#ascn', as: 'ascn'
get 'personals/ascname/*'=> 'personals#ascname', as: 'ascname'
get 'peronals/indexx' => 'personals#indexx', as: 'indexx'

  resources :professions, :sabhas, :families, :academics, :personals

get 'google' => redirect('http://www.google.com')

root 'personals#index' 

  
	

end

app/models/personal.rb
class Personal < ActiveRecord::Base
has_one :academic
has_one :family
has_one :sabha
has_one :profession
#validates_presence_of :name, :aygcode
  self.primary_key = 'aygcode'
end

app/controllers/personals_controller.rb
class PersonalsController < ApplicationController
  before_action :set_personal, only: [:show, :edit, :update, :destroy]

  # GET /personals
  # GET /personals.json
  def index
    @personals = Personal.order("aygcode ASC")
	
  end

  def ascn	
    @personals = Personal.order("aygcode ASC")
  end
  def ascname
      @personals = Personal.order("name ASC")
	render 'index'
  end
  # GET /personals/1
  # GET /personals/1.json
  def show
	 
  end

  # GET /personals/new
  def new
    @personal = Personal.new
  end

  # GET /personals/1/edit
  def edit
  end

  # POST /personals
  # POST /personals.json
  def create
    @personal = Personal.new(personal_params)

    respond_to do |format|
      if @personal.save
        format.html { redirect_to @personal, notice: 'Personal was successfully created.' }
	flash[:notice]
        format.json { render :show, status: :created, location: @personal }
      else
        format.html { render :new }
        format.json { render json: @personal.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /personals/1
  # PATCH/PUT /personals/1.json
  def update
    respond_to do |format|
      if @personal.update(personal_params)
        format.html { redirect_to @personal, notice: 'Personal was successfully updated.' }
        format.json { render :show, status: :ok, location: @personal }
      else
        format.html { render :edit }
        format.json { render json: @personal.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /personals/1
  # DELETE /personals/1.json
  def destroy
    @personal.destroy
    respond_to do |format|
      format.html { redirect_to personals_url, notice: 'Personal was successfully destroyed.' }
     format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_personal
      @personal = Personal.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def personal_params
      params.require(:personal).permit(:aygcode, :name, :dob, :doj, :contact1, :contact2, :email, :r_address, :r_area, :r_city, :r_state, :r_pincode, :profesion, :bloodgroup, :pan, :married, :anniversary_date, :interest)
    end
end

app/helpers/personals_helper.rb
module PersonalsHelper
end

app/views/personals/Link to _form.html.erb
/media/adminn/7438A90D38A8D002/OTHERS/AYGDB/aygdb/app/views/personals/_form.html.erb

app/views/personals/Link to _form_index.html.erb
/media/adminn/7438A90D38A8D002/OTHERS/AYGDB/aygdb/app/views/personals/_form_index.html.erb

app/views/personals/Link to ascn.html.erb
/media/adminn/7438A90D38A8D002/OTHERS/AYGDB/aygdb/app/views/personals/ascn.html.erb

app/views/personals/Link to index.html.erb
/media/adminn/7438A90D38A8D002/OTHERS/AYGDB/aygdb/app/views/personals/index.html.erb

app/views/personals/Link to indexx.html.erb
/media/adminn/7438A90D38A8D002/OTHERS/AYGDB/aygdb/app/views/personals/indexx.html.erb

app/views/personals/_form.html.erb
<h2><%= link_to 'Home', personals_path %></h2><br>




<%= button_to 'New', new_academic_path, :method => :get%>

  






<%= form_for(@personal) do |f| %>
  <% if @personal.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@personal.errors.count, "error") %> prohibited this personal from being saved:</h2>


      <ul>
      <% @personal.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :aygcode %>
    <%= f.text_field :aygcode %>
  </div>
  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :dob %>   
  <%= f.date_select :dob, :start_year=>1970,:end_year=>2015 %>
  </div>
  <div class="field">
    <%= f.label :doj %>
    <%= f.date_select :doj, :start_year=>1970,:end_year=>2030%>
  </div>
  <div class="field">
    <%= f.label :contact1 %>
    <%= f.text_field :contact1 %>
  </div>
  <div class="field">
    <%= f.label :contact2 %>
    <%= f.text_field :contact2 %>
  </div>
  <div class="field">
    <%= f.label :email %>
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :r_address %>
    <%= f.text_field :r_address %>
  </div>
  <div class="field">
    <%= f.label :r_area %>
    <%= f.text_field :r_area %>
  </div>
  <div class="field">
    <%= f.label :r_city %>
    <%= f.text_field :r_city %>
  </div>
  <div class="field">
    <%= f.label :r_state %>
    <%= f.text_field :r_state %>
  </div>
  <div class="field">
    <%= f.label :r_pincode %>
    <%= f.number_field :r_pincode, :size => 6%>
  </div>
  <div class="field">
    <%= f.label :profession %>
    <%= f.text_field :profesion %>
  </div>
  <div class="field">
    <%= f.label :bloodgroup %>
    <%= f.text_field :bloodgroup %>
  </div>
  <div class="field">
    <%= f.label :pan %>
    <%= f.text_field :pan %>
  </div>
  <div class="field">
    <%= f.label :married %>
    <%= f.check_box :married %>
  </div>
  <div class="field">
    <%= f.label :anniversary_date %>
    <%= f.date_select :anniversary_date, :start_year=>1970, :end_year=>2030%>
  </div>
  <div class="field">
    <%= f.label :interest %>
    <%= f.text_field :interest %>
  </div>
  <div class="actions">
	<%= f.submit  %>
    <% button_to "new", controller: "academics", action: "new" %>
  </div>
<% end %>

app/views/personals/_form_index.html.erb
<%= link_to 'Google', google_path %>
<p id="notice"><%= notice %></p>

<h2><%= link_to 'Home', personals_path %> </h2>
<table>
  <thead>
    <tr>
          <th colspan="3"></th>
<th>*****</th>
<th> <h3><%= link_to 'Aygcode', ascn_path %></h3></th>

      <th><h3><%= link_to 'Name', ascname_path %></th>
      <th>Dob</th>
      	<th>Age</th>	
      <th>Doj</th>
      <th>Contact1</th>
      <th>Contact2</th>
      <th><Email></th> 
      <th>R address</th>
      <th>R area</th> 
      <th>R city</th>
      <th>R state</th>
      <th>R pincode</th>
      <th>Profession</th>
      <th>Bloodgroup</th>
      <th>Pan</th>
      <th>Married</th>
      <th>Anniversary date</th>
      <th>Interest</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @personals.each do |personal| %>
      <tr>

    <td><%= link_to 'Show', personal %></td>
        <td><%= link_to 'Edit', edit_personal_path(personal) %></td>
        <td><%= link_to 'Destroy', personal, method: :delete
 %>
</td>


	          <td colspan="1"></td>
        <td><%= link_to personal.aygcode, personal_path(personal) %></td>
	<td><%= link_to personal.name, personal_path(personal) %></td>
        
        <td><%= personal.dob %></td>
	<td><%= Date.today-personal.dob %> </td>
        <td><%= personal.doj %></td>	
        <td><%= personal.contact1 %></td>
        <td><%= personal.contact2 %></td>
        <td><%= personal.email %></td>
        <td><%= personal.r_address %></td>
        <td><%= personal.r_area %></td>
        <td><%= personal.r_city %></td>
        <td><%= personal.r_state %></td>
        <td><%= personal.r_pincode %></td>
        <td><%= personal.profesion %></td>
        <td><%= personal.bloodgroup %></td>
        <td><%= personal.pan %></td>
        <td><%= personal.married %></td>
        <td><%= personal.anniversary_date %></td>
        <td><%= personal.interest %></td>
    
      </tr>
    <% end %>
  </tbody>
</table>

<br><br>

<h1> <%= link_to 'Add new ', new_personal_path %> </h1>

app/views/personals/ascn.html.erb
<%= render 'form_index' %>

app/views/personals/edit.html.erb
<%= render 'form' %>

<%= link_to 'Show', @personal %> |
<%= link_to 'Back', personals_path %>

app/views/personals/index.html.erb
<%= render 'form_index' %>

app/views/personals/indexx.html.erb
<%= render 'form_index' %>

app/views/personals/new.html.erb
<%= render 'form' %>

<%= link_to 'Add educational details', new_academic_path %>

app/views/personals/show.html.erb
<h2><%= link_to 'Home', personals_path %> </h2>
<p id="notice"><%= notice %></p>

<p>
  <strong>Aygcode:</strong>
  <%= @personal.aygcode %>
</p>

<p>
  <strong>Name:</strong>
  <%= @personal.name %>
</p>

<p>
  <strong>Dob:</strong>
  <%= @personal.dob %>
</p>

<p>
  <strong>Age:</strong>
  <%= Date.today-@personal.dob %>
</p>

<p>
  <strong>Doj:</strong>
  <%= @personal.doj %>
</p>

<p>
  <strong>Contact1:</strong>
  <%= @personal.contact1 %>
</p>

<p>
  <strong>Contact2:</strong>
  <%= @personal.contact2 %>
</p>

<p>
  <strong>Email:</strong>
  <%= @personal.email %>
</p>

<p>
  <strong>R address:</strong>
  <%= @personal.r_address %>
</p>

<p>
  <strong>R area:</strong>
  <%= @personal.r_area %>
</p>

<p>
  <strong>R city:</strong>
  <%= @personal.r_city %>
</p>

<p>
  <strong>R state:</strong>
  <%= @personal.r_state %>
</p>

<p>
  <strong>R pincode:</strong>
  <%= @personal.r_pincode %>
</p>

<p>
  <strong>Profession:</strong>
  <%= @personal.profesion %>
</p>

<p>
  <strong>Bloodgroup:</strong>
  <%= @personal.bloodgroup %>
</p>

<p>
  <strong>Pan:</strong>
  <%= @personal.pan %>
</p>

<p>
  <strong>Married:</strong>
  <%= @personal.married %>
</p>

<p>
  <strong>Anniversary date:</strong>
  <%= @personal.anniversary_date %>
</p>

<p>
  <strong>Interest:</strong>
  <%= @personal.interest %>
</p>

<%= link_to 'Edit', edit_personal_path(@personal) %> |
<%= link_to 'Back', personals_path %>